import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import connectMongo from "@/dbConnect/connectMongoose";
import { dbConnect } from "@/dbConnect/dbConnect";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Khana Khazana - Home",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  // await connectMongo()
  await dbConnect()
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
